title: CacheRoutes
modelClass: Octobro\SuperCache\Models\CacheRoute
list: $/octobro/supercache/models/cacheroute/columns.yaml
recordUrl: 'octobro/supercache/cacheroutes/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
defaultSort:
     column: sort_order
     direction: asc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
